// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEXT_RPG.Models
{
    public partial class CharacterData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public int LV { get; set; }
        public int EXP { get; set; }
        public int HP { get; set; }
        public int MP { get; set; }
        public int ATK { get; set; }
        public int DEF { get; set; }
        public int STR { get; set; }
        public int VIT { get; set; }
        public int AGI { get; set; }
        public int INT { get; set; }
        public int LUK { get; set; }
    }
}