// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEXT_RPG.Models
{
    public partial class ExpForm
    {
        public int Id { get; set; }
        public int LV { get; set; }
        public int EXP { get; set; }
    }
}