// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TEXT_RPG.Models
{
    public partial class SkillData
    {
        public int Id { get; set; }
        public string SkillName { get; set; }
        public string SkillInfo { get; set; }
        public string SkillClass { get; set; }
        public string SkillType { get; set; }
    }
}